# Chapter 5: The Basics of NumPy Arrays

## NumPy Array Attributes

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701) # for reproducibility

In [2]:
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3,4)) #two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3: dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3: dtype:  int64


## Array Indexing: Accessing Single Elements

Similar to Python's standard list indexing <br>
In a one-dimensional array, the ith value (counting from 0) can be accessed by specifying the desired index in quare brackets


In [4]:
x1

array([9, 4, 0, 3, 8, 6])

In [5]:
x1[0]

9

In [6]:
x1[4]

8

In [7]:
x1[-1]

6

In [8]:
x1[-2]

8

In a multidemensional arry, use a comma-separated (row, column) tuple:

In [10]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [11]:
x2[0, 0]

3

In [12]:
x2[2, 0]

0

In [13]:
x2[2, -1]

9

In [14]:
# modify values
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [15]:
# WARNING: fixed type so a floating point value in x1 will be truncated

x1[0] = 3.983247
x1

array([3, 4, 0, 3, 8, 6])

### Array Slicing: Accessing Subarrays

In [16]:
# x[start:stop:step]

x1

array([3, 4, 0, 3, 8, 6])

In [17]:
# First three elements
x1[:3]

array([3, 4, 0])

In [18]:
# Elements after index 3
x1[3:]

array([3, 8, 6])

In [19]:
# Middle subarray
x1[1:4]

array([4, 0, 3])

In [20]:
# Every second element
x1[::2]

array([3, 0, 8])

In [21]:
# Every second element, starting at index 1
x1[1::2]

array([4, 3, 6])

In [22]:
# All elements are reversed, (using a negative step)
x1[::-1]

array([6, 8, 3, 0, 4, 3])

In [23]:
# Every second element from index 4, reversed
x1[4::-2]

array([8, 0, 3])

### Multidimensional Subarrays

In [24]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [25]:
# First two rows and three columns
x2[:2, :3]

array([[12,  1,  3],
       [ 4,  0,  2]])

In [26]:
# Three rows, every second column
x2[:3, ::2]

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [27]:
# All rows and columns, reversed
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [29]:
# First column of x2
x2[:, 0]

array([12,  4,  0])

In [30]:
# First row of x2
x2[0, :]

array([12,  1,  3,  7])

In [31]:
# Or
x2[0]

array([12,  1,  3,  7])

### Subarrays as No-Copy Views

Unlike Python list slices, NumPy array slices are returned as "views" rather than "copies" of the array data

In [32]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [33]:
# Extract a 2 x 2 subarray
x2_sub = x2[:2, :2]

x2_sub

array([[12,  1],
       [ 4,  0]])

In [34]:
# If we modify this subarray, we'll see the original array is changed
x2_sub[0, 0] = 99

x2_sub

array([[99,  1],
       [ 4,  0]])

### Creating Copies of Arrays

In [35]:
x2_sub_copy = x2[:2, :2].copy()

x2_sub_copy

array([[99,  1],
       [ 4,  0]])

In [45]:
x2_sub_copy[0, 0] = 42

print("x2_sub_copy: \n", x2_sub_copy, "\n")

print("x2: \n", x2)

x2_sub_copy: 
 [[42  1]
 [ 4  0]] 

x2: 
 [[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


### Reshaping of Arrays



In [49]:
grid0 = np.arange(1, 10)

print("Grid without reshape: \n", grid0, "\n")

grid = np.arange(1, 10).reshape(3, 3)

print("Grid with reshape: \n", grid)

Grid without reshape: 
 [1 2 3 4 5 6 7 8 9] 

Grid with reshape: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
# Converting a one-dimensional array into a two-dimensional row or column matrix
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape

array([[1, 2, 3]])

In [55]:
x.reshape((3, 1)) # column vector via reshape

array([[1],
       [2],
       [3]])

In [56]:
# row vector via newaxis
x[np.newaxis, :] 

array([[1, 2, 3]])

In [57]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

In [58]:
# One-dimensional array
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [60]:
# Three one-dimensional arrays
z = np.array([99, 99, 99])
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [62]:
# Two-dimensional arrays 
grid = np.array([[1, 2, 3],
               [4, 5, 6]])

np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
# Two-dimensional arrays along axis = 1
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
# Arrays with mixed dimensions (use np.vstack (vertical stack) and np.hstack (horizontal stack))
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [71]:
y = np.array([[99],
          [99]])

np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting of Arrays

In [73]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

# Split on the points listed ie 3rd and 5th spot in array
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [75]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
upper, lower = np.vsplit(grid, [2])
print("upper: \n", upper, "\n")
print("lower: \n", lower)

upper: 
 [[0 1 2 3]
 [4 5 6 7]] 

lower: 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [78]:
left, right = np.hsplit(grid, [2])
print("left: \n", left, "\n")
print("right: \n", right)

left: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

right: 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
# for higher-dimensional arrays, np.dsplit will splitl arrays along the third axis