# Chapter 6 Computation on NumPy Arrays: Universal Functions

### The Slowness of Loops

In [2]:
# For example puposes, look at the time it takes for this loop to complete

import numpy as np
rng = np.random.default_rng(seed=1701)

In [6]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = rng.integers(1, 10, size=5)
print("values: \n", values)
compute_reciprocals(values)

values: 
 [7 4 2 4 8]


array([0.14285714, 0.25      , 0.5       , 0.25      , 0.125     ])

In [7]:
# Let's time how long it takes to calculate over a large array

big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.22 s ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
# Compare the results of the following two operations

print(compute_reciprocals(values))
print(1.0 / values)

[0.14285714 0.25       0.5        0.25       0.125     ]
[0.14285714 0.25       0.5        0.25       0.125     ]


In [11]:
# Completed in microseconds (on my machine)
%timeit (compute_reciprocals(values))

6.85 µs ± 99.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
# Completed in nanoseconds (less than the above) (on my machine)
%timeit (1.0 / values)

899 ns ± 23.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
# This 1.41 miliseconds is less than the 1.22 seconds seen above on the big_array using a loop
%timeit (1.0 / big_array)

1.41 ms ± 23.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
# Can also operate between two arrays

np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [15]:
print(np.arange(5))
print(np.arange(1, 6))

[0 1 2 3 4]
[1 2 3 4 5]


In [18]:
# Can also operate on multidimensional arrays as well
x = np.arange(9).reshape((3, 3))

print(x, "\n")
print(2 ** x)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


## Exploring NumPy's Ufuncs

Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two inputs.

### Array Arithmetic 

In [21]:
x = np.arange(4)

print("x     = ", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)
print("x // 2 = ", x // 2) # floor division
print("-x    = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

# Standard order of operations is respected
-(0.5*x +1) ** 2

x     =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]
-x    =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


array([-1.  , -2.25, -4.  , -6.25])

In [22]:
# All of these arithmetic operations are simply convenient wrappers around specific ufuncs built into NumPy.
# For example, the + operator is a wrapper for the add ufunc:

np.add(x, 2)

array([2, 3, 4, 5])

np.add <br>
np.subtract <br>
np.negative <br>
np.multiply <br>
np.divide <br>
np.floor_divide <br>
np.power <br>
np.mod <br>

### Absolute Value

Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [23]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [24]:
# The ufunc is np.absolute, which is also avalable under alias np.abs

print(np.absolute(x))

print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]


In [26]:
# Can also handle complex data, in which case it returns the magnitude:

x = np.array([3 - 4j, 4- 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric Functions

In [27]:
theta = np.linspace(0, np.pi, 3)

In [28]:
# Trig functions
print("theta         = ", theta)
print("sin(theta)    = ", np.sin(theta))
print("cos(theta)    = ", np.cos(theta))
print("tan(theta)    = ", np.tan(theta))

theta         =  [0.         1.57079633 3.14159265]
sin(theta)    =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)    =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)    =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [32]:
# Inverse Trig functions
x = [-1, 0, 1]
print("x            = ", x)
print("arcsin(x)    = ", np.arcsin(x))
print("arccos(x)    = ", np.arccos(x))
print("arctan(x)    = ", np.arctan(x))

x            =  [-1, 0, 1]
arcsin(x)    =  [-1.57079633  0.          1.57079633]
arccos(x)    =  [3.14159265 1.57079633 0.        ]
arctan(x)    =  [-0.78539816  0.          0.78539816]


### Exponents and Logarithms

In [33]:
x = [1, 2, 3]

print("x    = ", x)
print("e^x  = ", np.exp(x))
print("2^x  = ", np.exp2(x))
print("3^x  = ", np.power(3., x))

x    =  [1, 2, 3]
e^x  =  [ 2.71828183  7.3890561  20.08553692]
2^x  =  [2. 4. 8.]
3^x  =  [ 3.  9. 27.]


In [34]:
# The inverse of the exponentials, the logarithms, are also available

x = [1, 2, 4, 10]

print("x        = ", x)
print("ln(x)    = ", np.log(x))
print("log2(x)    = ", np.log2(x))
print("log10(x)    = ", np.log10(x))

x        =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)    =  [0.         1.         2.         3.32192809]
log10(x)    =  [0.         0.30103    0.60205999 1.        ]


In [35]:
# There are more precise versions too
# np.expm1()
# np.log1p()

### Specialized Ufuncs

In [40]:
!pip3 install scipy
from scipy import special

# many functions including gamma, beta, etc. 

ModuleNotFoundError: No module named 'scipy'

## Advanced Ufunc Features

### Specifying Output

In [41]:
# Specify the array where the result of the calculation will be stored

x = np.arange(5)
y = np.empty(5)

np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [42]:
# Can be used with array views
# Write the results of a computation to every other element of a specified array

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### Aggregations

In [45]:
# For binary ufuncs, aggregations can be computed directly from the object.

# We can reduce with a partiuclar operation ie repeatedly apply a given operation to 
# the elemnets of an array until only a single restult remains

x = np.arange(1, 6)
print("x: \n", x, "\n")
np.add.reduce(x)

x: 
 [1 2 3 4 5] 



15

In [46]:
x = np.arange(1, 6)
print("x: \n", x, "\n")
np.multiply.reduce(x)

x: 
 [1 2 3 4 5] 



120

In [47]:
# NOTE: There are dedicated NumPy functions for these particular cases
# np.sum, np.prod, np.cumsum, np.cumprod (Covered in Chapter 7)

### Outer Products

Any ufunc can compute the output of all pairs of two different inputs using the outer method. This allows you, in one line, to do things like create a multiplication table:

In [49]:
x = np.arange(1,6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [50]:
# There is more info on ufunc.at and ufunc.reduceat method in Chapter 10
# More information on broadcasting (ufuncs between arrays of differnet shapes and sizes) in Chapter 8